AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ManagedPolicy for nagiyu CloudFormation deploy operations (applied to CI/CD and local deploy users).

Resources:
  NagiyuDeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: nagiyu-deploy-policy
      Description: nagiyu リポジトリで CloudFormation によるデプロイを行うための最小権限ポリシー
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFormationOperations
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:ValidateTemplate
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:GetTemplateSummary
              - cloudformation:ListExports
            Resource: '*'

          - Sid: AllowECROperations
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: '*'

          - Sid: AllowECRRepositoryOperations
            Effect: Allow
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:DescribeRepositories
              - ecr:CreateRepository
              - ecr:TagResource
              - ecr:GetRepositoryPolicy
              - ecr:SetRepositoryPolicy
              - ecr:DeleteRepository
              - ecr:PutLifecyclePolicy
              - ecr:GetLifecyclePolicy
              - ecr:DeleteLifecyclePolicy
              - ecr:ListImages
            Resource: '*'

          - Sid: AllowECRRepositoryPolicyOperations
            Effect: Allow
            Action:
              - ecr:GetRepositoryPolicy
              - ecr:SetRepositoryPolicy
            Resource: '*'

          - Sid: AllowCloudWatchLogsOperations
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:TagResource
              - logs:UntagResource
              - logs:DeleteLogGroup
              - logs:DeleteLogStream
              - logs:PutRetentionPolicy
            Resource: '*'

          - Sid: AllowEC2Operations
            Effect: Allow
            Action:
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:RevokeSecurityGroupEgress
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:CreateTags
            Resource: '*'

          - Sid: AllowBatchManagement
            Effect: Allow
            Action:
              - batch:CreateComputeEnvironment
              - batch:DeleteComputeEnvironment
              - batch:UpdateComputeEnvironment
              - batch:CreateJobQueue
              - batch:DeleteJobQueue
              - batch:UpdateJobQueue
              - batch:RegisterJobDefinition
              - batch:DeregisterJobDefinition
              - batch:TagResource
              - batch:UntagResource
            Resource: '*'

          - Sid: AllowCreateServiceLinkedRole
            Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource: '*'

          - Sid: AllowS3BucketCreation
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:PutBucketPolicy
              - s3:PutBucketTagging
              - s3:DeleteBucket
              - s3:ListAllMyBuckets
              - s3:PutEncryptionConfiguration
              - s3:PutLifecycleConfiguration
              - s3:PutBucketCORS
              - s3:PutBucketPublicAccessBlock
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
              - s3:AbortMultipartUpload
            Resource: '*'

          - Sid: AllowS3Operations
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource: '*'

          - Sid: AllowIAMRoleCreation
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:AttachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRole
              - iam:DetachRolePolicy
              - iam:DeleteRolePolicy
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:ListAccessKeys
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:GetUser
              - iam:CreateUser
              - iam:DeleteUser
              - iam:AttachUserPolicy
              - iam:DetachUserPolicy
              - iam:PutUserPolicy
              - iam:TagUser
              - iam:GetRole
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListRolePolicies
              - iam:ListUserPolicies
              - iam:GetRolePolicy
              - iam:GetUserPolicy
              - iam:GetAccessKeyLastUsed
              - iam:ListUsers
              - iam:ListGroups
              - iam:GetGroup
              - iam:ListGroupPolicies
              - iam:GetGroupPolicy
              - iam:TagRole
            Resource: '*'

          - Sid: AllowPassRole
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: '*'
            Condition:
              StringEquals:
                iam:PassedToService:
                  - lambda.amazonaws.com
                  - batch.amazonaws.com
                  - ecs-tasks.amazonaws.com

          - Sid: AllowLambdaOperations
            Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:GetFunction
              - lambda:DeleteFunction
              - lambda:PublishVersion
              - lambda:CreateAlias
              - lambda:UpdateAlias
              - lambda:GetAlias
              - lambda:ListVersionsByFunction
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:CreateFunctionUrlConfig
              - lambda:UpdateFunctionUrlConfig
              - lambda:GetFunctionUrlConfig
              - lambda:DeleteFunctionUrlConfig
            Resource: '*'

          - Sid: AllowBatchOperations
            Effect: Allow
            Action:
              - batch:RegisterJobDefinition
              - batch:DeregisterJobDefinition
              - batch:DescribeJobDefinitions
              - batch:DescribeComputeEnvironments
              - batch:DescribeJobQueues
            Resource: '*'

          - Sid: AllowDynamoDBOperations
            Effect: Allow
            Action:
              - dynamodb:CreateTable
              - dynamodb:DeleteTable
              - dynamodb:UpdateTable
              - dynamodb:DescribeTable
              - dynamodb:ListTables
              - dynamodb:TagResource
              - dynamodb:UntagResource
              - dynamodb:UpdateTimeToLive
              - dynamodb:DescribeTimeToLive
              - dynamodb:UpdateContinuousBackups
              - dynamodb:DescribeContinuousBackups
            Resource: '*'

          - Sid: AllowCloudFrontOperations
            Effect: Allow
            Action:
              - cloudfront:CreateDistribution
              - cloudfront:UpdateDistribution
              - cloudfront:DeleteDistribution
              - cloudfront:GetDistribution
              - cloudfront:GetDistributionConfig
              - cloudfront:ListDistributions
              - cloudfront:CreateInvalidation
              - cloudfront:GetInvalidation
              - cloudfront:TagResource
              - cloudfront:UntagResource
            Resource: '*'

          - Sid: AllowAPIGatewayOperations
            Effect: Allow
            Action:
              - apigatewayv2:CreateApi
              - apigatewayv2:UpdateApi
              - apigatewayv2:DeleteApi
              - apigatewayv2:GetApi
              - apigatewayv2:CreateRoute
              - apigatewayv2:CreateIntegration
              - apigatewayv2:CreateStage
              - apigatewayv2:DeployApi
              - apigatewayv2:GetDeployments
              - apigatewayv2:TagResource
              - apigatewayv2:UntagResource
            Resource: '*'

Outputs:
  NagiyuDeployPolicyArn:
    Description: Managed policy ARN for nagiyu deploy operations
    Value: !Ref NagiyuDeployPolicy
    Export:
      Name: nagiyu-deploy-policy-arn
