AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation skeleton for Codec Converter service.
  Includes placeholders for S3, DynamoDB, Batch, IAM, and ECR resources.
  This is a minimal skeleton template - detailed design will be completed in separate tasks.

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev or prod)
    AllowedValues:
      - dev
      - prod
    Default: dev

  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: codec-converter

Conditions:
  IsDevEnvironment: !Equals [!Ref Environment, dev]
  IsProdEnvironment: !Equals [!Ref Environment, prod]

Resources:
  # ==========================================
  # ECR - Container Image Repositories
  # ==========================================
  
  # ECR repository for Next.js application container
  NextJsEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-nextjs-${Environment}'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-nextjs-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # ECR repository for FFmpeg worker container
  FfmpegEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-ffmpeg-${Environment}'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-ffmpeg-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # IAM - Roles and Policies
  # ==========================================
  
  # IAM role for Lambda function execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${StorageBucket.Arn}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !GetAtt JobsTable.Arn
        - PolicyName: BatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - batch:SubmitJob
                  - batch:DescribeJobs
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-lambda-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # IAM role for Batch job execution (task role)
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-batch-job-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${StorageBucket.Arn}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt JobsTable.Arn
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-batch-job-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # IAM role for Batch execution (execution role for Fargate)
  BatchExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-batch-execution-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-batch-execution-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # S3 - Storage Bucket
  # ==========================================
  
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter24Hours
            Status: Enabled
            ExpirationInDays: 1
            Prefix: ''
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - !If
                - IsDevEnvironment
                - 'http://localhost:3000'
                - 'https://codec-converter.example.com'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3600
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-storage-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # DynamoDB - Jobs Table
  # ==========================================
  
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-jobs-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiresAt
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-jobs-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # AWS Batch - Compute Environment
  # ==========================================
  
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub '${ProjectName}-compute-env-${Environment}'
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 6
        Subnets:
          - !ImportValue nagiyu-dev-vpc-private-subnet-1
          - !ImportValue nagiyu-dev-vpc-private-subnet-2
        SecurityGroupIds:
          - !ImportValue nagiyu-dev-vpc-default-security-group
      Tags:
        Name: !Sub '${ProjectName}-compute-env-${Environment}'
        Environment: !Ref Environment

  # ==========================================
  # AWS Batch - Job Queue
  # ==========================================
  
  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub '${ProjectName}-job-queue-${Environment}'
      State: ENABLED
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      Tags:
        Name: !Sub '${ProjectName}-job-queue-${Environment}'
        Environment: !Ref Environment

  # ==========================================
  # AWS Batch - Job Definition
  # ==========================================
  
  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub '${ProjectName}-job-definition-${Environment}'
      Type: container
      PlatformCapabilities:
        - FARGATE
      Parameters: {}
      Timeout:
        AttemptDurationSeconds: 7200
      RetryStrategy:
        Attempts: 1
      ContainerProperties:
        Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FfmpegEcrRepository}:latest'
        JobRoleArn: !GetAtt BatchJobRole.Arn
        ExecutionRoleArn: !GetAtt BatchExecutionRole.Arn
        ResourceRequirements:
          - Type: VCPU
            Value: '2'
          - Type: MEMORY
            Value: '4096'
        Environment:
          - Name: S3_BUCKET
            Value: !Ref StorageBucket
          - Name: DYNAMODB_TABLE
            Value: !Ref JobsTable
          - Name: AWS_REGION
            Value: !Ref AWS::Region
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref BatchLogGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: batch
      Tags:
        Name: !Sub '${ProjectName}-job-definition-${Environment}'
        Environment: !Ref Environment

  # ==========================================
  # CloudWatch Logs - Log Groups
  # ==========================================
  
  BatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/batch/${ProjectName}-${Environment}'
      RetentionInDays: 7

Outputs:
  # ECR Repository URLs
  NextJsEcrRepositoryUri:
    Description: URI of the Next.js ECR repository
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${NextJsEcrRepository}'
    Export:
      Name: !Sub '${ProjectName}-nextjs-ecr-uri-${Environment}'

  FfmpegEcrRepositoryUri:
    Description: URI of the FFmpeg ECR repository
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FfmpegEcrRepository}'
    Export:
      Name: !Sub '${ProjectName}-ffmpeg-ecr-uri-${Environment}'

  # IAM Role ARNs
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-lambda-role-arn-${Environment}'

  BatchJobRoleArn:
    Description: ARN of the Batch job role
    Value: !GetAtt BatchJobRole.Arn
    Export:
      Name: !Sub '${ProjectName}-batch-job-role-arn-${Environment}'

  BatchExecutionRoleArn:
    Description: ARN of the Batch execution role
    Value: !GetAtt BatchExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-batch-execution-role-arn-${Environment}'

  # S3 Bucket
  StorageBucketName:
    Description: Name of the S3 storage bucket
    Value: !Ref StorageBucket
    Export:
      Name: !Sub '${ProjectName}-s3-bucket-name-${Environment}'

  StorageBucketArn:
    Description: ARN of the S3 storage bucket
    Value: !GetAtt StorageBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-s3-bucket-arn-${Environment}'

  # DynamoDB Table
  JobsTableName:
    Description: Name of the DynamoDB jobs table
    Value: !Ref JobsTable
    Export:
      Name: !Sub '${ProjectName}-dynamodb-table-name-${Environment}'

  JobsTableArn:
    Description: ARN of the DynamoDB jobs table
    Value: !GetAtt JobsTable.Arn
    Export:
      Name: !Sub '${ProjectName}-dynamodb-table-arn-${Environment}'

  # Batch Resources
  BatchComputeEnvironmentArn:
    Description: ARN of the Batch compute environment
    Value: !Ref BatchComputeEnvironment
    Export:
      Name: !Sub '${ProjectName}-batch-compute-env-arn-${Environment}'

  BatchJobQueueArn:
    Description: ARN of the Batch job queue
    Value: !Ref BatchJobQueue
    Export:
      Name: !Sub '${ProjectName}-batch-queue-arn-${Environment}'

  BatchJobDefinitionArn:
    Description: ARN of the Batch job definition
    Value: !Ref BatchJobDefinition
    Export:
      Name: !Sub '${ProjectName}-batch-job-definition-arn-${Environment}'

  # CloudWatch Logs
  BatchLogGroupName:
    Description: Name of the Batch CloudWatch log group
    Value: !Ref BatchLogGroup
    Export:
      Name: !Sub '${ProjectName}-batch-log-group-name-${Environment}'
