AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB User Table for Auth Service'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
    Description: Environment name (dev/prod)

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  AuthUsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      TableName: !Sub 'nagiyu-auth-users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: googleId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: googleId-index
          KeySchema:
            - AttributeName: googleId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: nagiyu
        - Key: Service
          Value: auth
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: User information storage

Outputs:
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref AuthUsersTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt AuthUsersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'

  GoogleIdIndexName:
    Description: GoogleId GSI Name
    Value: googleId-index
    Export:
      Name: !Sub '${AWS::StackName}-GoogleIdIndexName'
