AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager for Auth Service OAuth Credentials'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]
    Default: dev
    Description: Environment name (dev/staging/prod)

Resources:
  GoogleOAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'nagiyu-auth-google-oauth-${Environment}'
      Description: Google OAuth credentials for Auth service
      SecretString: |
        {
          "clientId": "PLACEHOLDER_CLIENT_ID",
          "clientSecret": "PLACEHOLDER_CLIENT_SECRET"
        }
      Tags:
        - Key: Application
          Value: nagiyu
        - Key: Service
          Value: auth
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Google OAuth credentials

  NextAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'nagiyu-auth-nextauth-secret-${Environment}'
      Description: NextAuth.js secret key for JWT signing
      GenerateSecretString:
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Application
          Value: nagiyu
        - Key: Service
          Value: auth
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: NextAuth.js JWT signing key

Outputs:
  GoogleOAuthSecretArn:
    Description: Google OAuth Secret ARN
    Value: !Ref GoogleOAuthSecret
    Export:
      Name: !Sub '${AWS::StackName}-GoogleOAuthSecretArn'

  GoogleOAuthSecretName:
    Description: Google OAuth Secret Name
    Value: !Sub 'nagiyu-auth-google-oauth-${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-GoogleOAuthSecretName'

  NextAuthSecretArn:
    Description: NextAuth Secret ARN
    Value: !Ref NextAuthSecret
    Export:
      Name: !Sub '${AWS::StackName}-NextAuthSecretArn'

  NextAuthSecretName:
    Description: NextAuth Secret Name
    Value: !Sub 'nagiyu-auth-nextauth-secret-${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-NextAuthSecretName'
