AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM User for nagiyu local developers. This user attaches the shared managed policy.
  AccessKey/SecretAccessKey の発行はセキュリティ上コンソールで手動発行してください（テンプレートでは自動生成しません）。

Resources:
  NagiyuLocalDevUser:
    Type: AWS::IAM::User
    Properties:
      UserName: nagiyu-local-dev
      ManagedPolicyArns:
        - !ImportValue nagiyu-deploy-policy-core-arn
        - !ImportValue nagiyu-deploy-policy-container-arn
        - !ImportValue nagiyu-deploy-policy-application-arn
        - !ImportValue nagiyu-deploy-policy-integration-arn
      Tags:
        - Key: Application
          Value: nagiyu
        - Key: Purpose
          Value: Local developer

Outputs:
  NagiyuLocalDevUserName:
    Description: Local developer user name
    Value: !Ref NagiyuLocalDevUser
    Export:
      Name: !Sub '${AWS::StackName}-NagiyuLocalDevUserName'

  NagiyuLocalDevUserArn:
    Description: Local developer user ARN
    Value: !GetAtt NagiyuLocalDevUser.Arn
    Export:
      Name: !Sub '${AWS::StackName}-NagiyuLocalDevUserArn'
