AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for Tools Application'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
  
  RepositoryName:
    Type: String
    Default: tools-app

Resources:
  ToolsECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${RepositoryName}-${Environment}'
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ToolsECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryUri'
  
  RepositoryArn:
    Description: ECR Repository ARN
    Value: !GetAtt ToolsECRRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryArn'
