AWSTemplateFormatVersion: '2010-09-09'
Description: ACM Certificate for nagiyu platform (wildcard certificate for CloudFront)

Parameters:
  DomainName:
    Type: String
    Description: Primary domain name (e.g., example.com)
    AllowedPattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]\.[a-z]{2,}$
    ConstraintDescription: Must be a valid domain name

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub '*.${DomainName}'
      ValidationMethod: DNS
      Tags:
        - Key: Application
          Value: nagiyu
        - Key: Purpose
          Value: SSL/TLS certificate for CloudFront
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  CertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref Certificate
    Export:
      Name: nagiyu-shared-acm-certificate-arn

  DomainName:
    Description: Primary domain name
    Value: !Ref DomainName
    Export:
      Name: nagiyu-shared-acm-domain-name

  WildcardDomain:
    Description: Wildcard domain name
    Value: !Sub '*.${DomainName}'
    Export:
      Name: nagiyu-shared-acm-wildcard-domain
